# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 783389ada079bca06d64cba70d5042e32074c3cc5356d669904566b9bf2b30c5f332e66dc468c2aba5f5d2a2cca277169dcd3e99cfbd312f4a0f5fe635c05465

test:
  secret_key_base: 1ef1e050f42707a06aa6f99ed3893d2f3e95c77e961a4a6dc2e6e125204e6972ee2018450d42ab4283b3edc95f7be2f590ba67636262d903351c0af71507bc03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
